### ISSUE TITLE
Crash on deny enter 

### ISSUE THREAD

**Issue by LucasPMagno** [GameModsBR/MineCity#55]
Using Forge 1.7.10 with NEI, NEIIntegration, Translocator, EnderStorage, CodeChickenCore, CodeChickenLib and ForgeMultiPart when /nature deny enter going from a city to nature it crashes

Here is the log, it begins when I deny the permission to nature
```
[11:04:59] [Client thread/INFO]: [CHAT] MineCity> The permission was denied successfully
[11:05:03] [Client thread/INFO]: [CHAT] You don't have permission to perform this action.
[11:05:03] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$PlayerTickEvent@157d746e:
java.lang.NoSuchMethodError: net.minecraft.entity.Entity.setPositionAndUpdate(DDD)V
	at br.com.gamemods.minecity.forge.base.accessors.entity.base.IEntityPlayerMP.teleport(IEntityPlayerMP.java:98) ~[IEntityPlayerMP.class:?]
	at br.com.gamemods.minecity.forge.base.command.ForgePlayerSender.teleport(ForgePlayerSender.java:81) ~[ForgePlayerSender.class:?]
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.checkPosition(ForgePlayer.java:170) ~[ForgePlayer.class:?]
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.tick(ForgePlayer.java:84) ~[ForgePlayer.class:?]
	at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenTickListener.onPlayerTick(SevenTickListener.java:23) ~[SevenTickListener.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_SevenTickListener_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:259) [EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330) [EntityPlayerMP.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:329) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37) [C03PacketPlayer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.processPacket(C03PacketPlayer.java:163) [C03PacketPlayer$C04PacketPlayerPosition.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) [NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
[11:05:03] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[11:05:03] [Server thread/ERROR] [FML]: 0: NORMAL
[11:05:03] [Server thread/ERROR] [FML]: 1: ASM: codechicken.nei.ServerHandler@23e4e65e tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:05:03] [Server thread/ERROR] [FML]: 2: ASM: br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenTickListener@cb3fd69 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:05:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:198) ~[NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.setPositionAndUpdate(DDD)V
	at br.com.gamemods.minecity.forge.base.accessors.entity.base.IEntityPlayerMP.teleport(IEntityPlayerMP.java:98) ~[IEntityPlayerMP.class:?]
	at br.com.gamemods.minecity.forge.base.command.ForgePlayerSender.teleport(ForgePlayerSender.java:81) ~[ForgePlayerSender.class:?]
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.checkPosition(ForgePlayer.java:170) ~[ForgePlayer.class:?]
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.tick(ForgePlayer.java:84) ~[ForgePlayer.class:?]
	at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenTickListener.onPlayerTick(SevenTickListener.java:23) ~[SevenTickListener.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_SevenTickListener_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:259) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330) ~[EntityPlayerMP.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:329) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37) ~[C03PacketPlayer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.processPacket(C03PacketPlayer.java:163) ~[C03PacketPlayer$C04PacketPlayerPosition.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) ~[NetworkSystem.class:?]
	... 5 more
[11:05:03] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Lucas Magno\IdeaProjects\MineCity\Forge\1.7.10\run\.\crash-reports\crash-2016-09-10_11.05.03-server.txt
[11:05:03] [Server thread/INFO]: Stopping server
[11:05:03] [Server thread/INFO]: Saving players
[11:05:04] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// Oops.

Time: 10/09/16 11:05
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.setPositionAndUpdate(DDD)V
	at br.com.gamemods.minecity.forge.base.accessors.entity.base.IEntityPlayerMP.teleport(IEntityPlayerMP.java:98)
	at br.com.gamemods.minecity.forge.base.command.ForgePlayerSender.teleport(ForgePlayerSender.java:81)
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.checkPosition(ForgePlayer.java:170)
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.tick(ForgePlayer.java:84)
	at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenTickListener.onPlayerTick(SevenTickListener.java:23)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_SevenTickListener_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:259)
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330)
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:329)
	at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.processPacket(C03PacketPlayer.java:163)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at br.com.gamemods.minecity.forge.base.accessors.entity.base.IEntityPlayerMP.teleport(IEntityPlayerMP.java:98)
	at br.com.gamemods.minecity.forge.base.command.ForgePlayerSender.teleport(ForgePlayerSender.java:81)
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.checkPosition(ForgePlayer.java:170)
	at br.com.gamemods.minecity.forge.base.command.ForgePlayer.tick(ForgePlayer.java:84)
	at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenTickListener.onPlayerTick(SevenTickListener.java:23)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_SevenTickListener_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:259)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 167
	Entity Name: Player154
	Entity's Exact location: 400,09, 69,60, 9,46
	Entity's Block location: World: (400,69,9), Chunk: (at 0,4,9 in 25,0; contains blocks 400,0,0 to 415,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330)
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:329)
	at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.processPacket(C03PacketPlayer.java:163)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@427da7f4
Stacktrace:
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 715833248 bytes (682 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	minecity{1.0.0-SNAPSHOT} [MineCity] (main) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
	UCHIJAAAA	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-gamemods2-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Player154'/167, l='New World', x=400,09, y=69,60, z=9,46]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[11:05:04] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:393]: #@!@# Game crashed! Crash report saved to: #@!@# .\crash-reports\crash-2016-09-10_11.05.03-server.txt
[11:05:04] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[11:05:04] [Server thread/INFO]: Saving worlds
[11:05:04] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[11:05:04] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[11:05:04] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[11:05:04] [Server thread/INFO] [FML]: Unloading dimension 0
[11:05:04] [Server thread/INFO] [FML]: Unloading dimension -1
[11:05:04] [Server thread/INFO] [FML]: Unloading dimension 1
[11:05:04] [Server thread/INFO] [FML]: Applying holder lookups
[11:05:04] [Server thread/INFO] [FML]: Holder lookups applied
[11:05:04] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[11:05:04] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

Process finished with exit code -1
```

**Comment by joserobjr** [comment]
Thank you
