### ISSUE TITLE
Error on deny harvest

### ISSUE THREAD

**Issue by LucasPMagno** [GameModsBR/MineCity#56]
Using Forge 1.7.10 with NEI, NEIIntegration, Translocator, EnderStorage, CodeChickenCore, CodeChickenLib and ForgeMultiPart by using command /nature deny harvest (/city deny harvest gives same result)
Log upon execution:
```
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: br.com.gamemods.minecity.datasource.api.DataSourceException: java.sql.SQLException: Data truncated for column 'perm' at row 1
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.datasource.sql.SQLPermStorage.deny(SQLPermStorage.java:434)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.datasource.api.SimpleStorageHolder$SimpleMap.put(SimpleStorageHolder.java:95)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.datasource.api.SimpleStorageHolder$SimpleMap.put(SimpleStorageHolder.java:83)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.api.permission.SimpleFlagHolder.deny(SimpleFlagHolder.java:104)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.datasource.api.SimpleStorageHolder.deny(SimpleStorageHolder.java:66)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.commands.PermissionCommands.denyNature(PermissionCommands.java:447)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.commands.PermissionCommands.lambda$register$15(PermissionCommands.java:87)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.api.command.PlayerCommand.execute(PlayerCommand.java:13)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.api.command.CommandFunction.apply(CommandFunction.java:16)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.api.command.CommandFunction.run(CommandFunction.java:41)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.api.command.CommandTree$Result.run(CommandTree.java:1027)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.api.command.CommandTree.lambda$invoke$1(CommandTree.java:72)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.sql.SQLException: Data truncated for column 'perm' at row 1
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4208)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2758)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2826)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.datasource.sql.SQLSource.executeUpdate(SQLSource.java:158)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at br.com.gamemods.minecity.datasource.sql.SQLPermStorage.deny(SQLPermStorage.java:418)
[11:24:29] [pool-4-thread-13/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 16 more
[11:24:29] [Client thread/INFO]: [CHAT] MineCity> Oops.. An error occurred while executing this command: DataSourceException: java.sql.SQLException: Data truncated for column 'perm' at row 1  
```

**Comment by joserobjr** [comment]
I think that your database is outdated or it has failed to update to version 2.

What's is the `value` inside the table `minecity_setup`?

**Comment by joserobjr** [comment]
I've found the issue, the permission is missing in the initial setup file, thank you.
