### ISSUE TITLE
NPE on /city go

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#76]
```java
titaneo issued server command: /c ir Amestris
java.lang.NullPointerException
       at br.com.gamemods.minecity.datasource.sql.SQLCityStorage.loadPlots(SQLCityStorage.java:1401)
       at br.com.gamemods.minecity.structure.Island.<init>(Island.java:52)
       at br.com.gamemods.minecity.datasource.sql.SQLIsland.<init>(SQLIsland.java:44)
       at br.com.gamemods.minecity.datasource.sql.SQLSource.loadIslands(SQLSource.java:83)
       at br.com.gamemods.minecity.datasource.sql.SQLSource.loadCity(SQLSource.java:156)
       at br.com.gamemods.minecity.datasource.sql.SQLSource.getCityByName(SQLSource.java:632)
       at br.com.gamemods.minecity.commands.CityCommand.spawn(CityCommand.java:573)
       at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:497)
       at br.com.gamemods.minecity.api.command.CommandTree.lambda$registerCommand$4(CommandTree.java:124)
       at br.com.gamemods.minecity.api.command.CommandTree$$Lambda$371/691866799.execute(Unknown Source)
       at br.com.gamemods.minecity.api.command.CommandFunction.apply(CommandFunction.java:16)
       at br.com.gamemods.minecity.api.command.CommandFunction.run(CommandFunction.java:41)
       at br.com.gamemods.minecity.api.command.CommandTree$Result.run(CommandTree.java:1058)
       at br.com.gamemods.minecity.api.command.CommandTree.lambda$invoke$1(CommandTree.java:72)
       at br.com.gamemods.minecity.api.command.CommandTree$$Lambda$512/224084897.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at java.lang.Thread.run(Thread.java:745)
```

**Comment by joserobjr** [comment]
Duplicated to #81
