### ISSUE TITLE
SAXException on /city perms

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#82]
```java
[18:31:05] [Server thread/INFO]: D4rkness_King issued server command: /cidade perms
[18:31:05] [pool-6-thread-3777/WARN]: java.lang.RuntimeException: org.xml.sax.SAXException: Message: <msg><green>${perm}</green></msg>
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
  at br.com.gamemods.minecity.api.command.MessageTransformer$TextComponent.replace(MessageTransformer.java:837)
  at br.com.gamemods.minecity.api.command.MessageTransformer$Component.apply(MessageTransformer.java:552)
  at br.com.gamemods.minecity.forge.mc_1_7_10.command.SevenTransformer.toMultilineForge(SevenTransformer.java:64)
  at br.com.gamemods.minecity.forge.mc_1_7_10.command.SevenTransformer.send(SevenTransformer.java:29)
  at br.com.gamemods.minecity.forge.mc_1_7_10.command.SevenTransformer.send(SevenTransformer.java:40)
  at br.com.gamemods.minecity.forge.base.command.ForgeCommandSender.send(ForgeCommandSender.java:76)
  at br.com.gamemods.minecity.commands.PermissionCommands.list(PermissionCommands.java:387)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at br.com.gamemods.minecity.api.command.CommandTree.lambda$registerCommand$4(CommandTree.java:124)
  at br.com.gamemods.minecity.api.command.CommandTree$$Lambda$371/691866799.execute(Unknown Source)
  at br.com.gamemods.minecity.api.command.CommandFunction.apply(CommandFunction.java:16)
  at br.com.gamemods.minecity.api.command.CommandFunction.run(CommandFunction.java:41)
  at br.com.gamemods.minecity.api.command.CommandTree$Result.run(CommandTree.java:1058)
  at br.com.gamemods.minecity.api.command.CommandTree.lambda$invoke$1(CommandTree.java:72)
  at br.com.gamemods.minecity.api.command.CommandTree$$Lambda$512/224084897.run(Unknown Source)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXException: Message: <msg><green>${perm}</green></msg>
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
  at br.com.gamemods.minecity.api.command.MessageTransformer.parse(MessageTransformer.java:146)
  at br.com.gamemods.minecity.api.command.MessageTransformer$TextComponent.replace(MessageTransformer.java:833)
  ... 22 more
Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
  at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:271)
  at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
  at br.com.gamemods.minecity.api.command.MessageTransformer.parse(MessageTransformer.java:137)
  ... 23 more
```

**Comment by joserobjr** [comment]
Cause: DocumentBuilder is not thread safe
