### ISSUE TITLE
CityID not found

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#87]
```java
0:43:31 INFO]: Esctogrillo issued server command: /cidade spawn kingdom-centro
[10:43:32 ERROR]: Failed to load the chunk: ChunkPos{world=WorldDim{dim=0, dir='world'}, x=297, z=129}
br.com.gamemods.minecity.datasource.api.DataSourceException: City ID 46 not found
        at br.com.gamemods.minecity.datasource.sql.SQLSource.lambda$city$5(SQLSource.java:339) ~[SQLSource.class:?]
        at br.com.gamemods.minecity.datasource.sql.SQLSource$$Lambda$433/1513723818.get(Unknown Source) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_45]
        at br.com.gamemods.minecity.datasource.sql.SQLSource.city(SQLSource.java:339) ~[SQLSource.class:?]
        at br.com.gamemods.minecity.datasource.sql.SQLSource.getCityChunk(SQLSource.java:370) ~[SQLSource.class:?]
        at br.com.gamemods.minecity.MineCity.loadChunk(MineCity.java:243) ~[MineCity.class:?]
        at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenWorldListener.lambda$onChunkLoad$0(SevenWorldListener.java:41) [SevenWorldListener.class:?]
        at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenWorldListener$$Lambda$423/2121905363.run(Unknown Source) [SevenWorldListener.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

Other:
```java
[10:46:02 INFO]: [Server thread] Server side modded connection established
[10:46:02 INFO]: lucaszainko[/191.250.115.214:2456] logged in with entity id 2991 at ([mina] -51.3945807864617, 78.0, 291.28176789485195)
[10:46:02 ERROR]: Failed to load the chunk: ChunkPos{world=WorldDim{dim=3, dir='world/DIM3'}, x=5, z=15}
br.com.gamemods.minecity.datasource.api.DataSourceException: City ID 12 not found
        at br.com.gamemods.minecity.datasource.sql.SQLSource.lambda$city$5(SQLSource.java:339) ~[SQLSource.class:?]
        at br.com.gamemods.minecity.datasource.sql.SQLSource$$Lambda$433/1513723818.get(Unknown Source) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_45]
        at br.com.gamemods.minecity.datasource.sql.SQLSource.city(SQLSource.java:339) ~[SQLSource.class:?]
        at br.com.gamemods.minecity.datasource.sql.SQLSource.getCityChunk(SQLSource.java:370) ~[SQLSource.class:?]
        at br.com.gamemods.minecity.MineCity.loadChunk(MineCity.java:243) ~[MineCity.class:?]
        at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenWorldListener.lambda$onChunkLoad$0(SevenWorldListener.java:41) [SevenWorldListener.class:?]
        at br.com.gamemods.minecity.forge.mc_1_7_10.listeners.SevenWorldListener$$Lambda$423/2121905363.run(Unknown Source) [SevenWorldListener.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by joserobjr** [comment]
minecity_claims is missing the foreign keys.
