### ISSUE TITLE
NoSuchElementException on /city claim

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/MineCity#88]
```java
[12:34:58] [pool-6-thread-2599/WARN]: java.util.NoSuchElementException: No value present
[12:34:58] [pool-6-thread-2599/WARN]:   at java.util.Optional.get(Optional.java:135)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.commands.CityCommand.claim(CityCommand.java:334)
[12:34:58] [pool-6-thread-2599/WARN]:   at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
[12:34:58] [pool-6-thread-2599/WARN]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:34:58] [pool-6-thread-2599/WARN]:   at java.lang.reflect.Method.invoke(Method.java:497)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandTree.lambda$registerCommand$4(CommandTree.java:124)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandTree$$Lambda$371/486232168.execute(Unknown Source)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandFunction.apply(CommandFunction.java:16)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandFunction.run(CommandFunction.java:41)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandTree$Result.run(CommandTree.java:1058)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandTree.lambda$invoke$1(CommandTree.java:72)
[12:34:58] [pool-6-thread-2599/WARN]:   at br.com.gamemods.minecity.api.command.CommandTree$$Lambda$483/1522059954.run(Unknown Source)
[12:34:58] [pool-6-thread-2599/WARN]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:34:58] [pool-6-thread-2599/WARN]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:34:58] [pool-6-thread-2599/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:34:58] [pool-6-thread-2599/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:34:58] [pool-6-thread-2599/WARN]:   at java.lang.Thread.run(Thread.java:745)
```

**Comment by joserobjr** [comment]
Seems to be fixed by 31739f1c35a9f76de2c476312e9794c0bb797f87 too
